Ext.Osiris.RegisterListener("LevelGameplayStarted", 2, "after", function(level, isEditorMode)
    local squadies = Osi.DB_PartOfTheTeam:Get(nil)
    for _,k in pairs(squadies) do
		AddSpell(k[1], "Target_Shove_Trip", 1, 1)
		AddSpell(k[1], "Target_Swap", 1, 1)
		AddSpell(k[1], "Target_Feint", 1, 1)
		AddSpell(k[1], "Shout_Skilled_Hide", 1, 1)
		AddSpell(k[1], "Target_Recall_Knowledge_Arcana", 1, 1)
		AddSpell(k[1], "Target_Recall_Knowledge_History", 1, 1)
		AddSpell(k[1], "Target_Recall_Knowledge_Nature", 1, 1)
		AddSpell(k[1], "Target_Recall_Knowledge_Religion", 1, 1)
		AddSpell(k[1], "Target_Find_Weak_Spot_Investigation", 1, 1)
		AddSpell(k[1], "Target_Handle_Animal", 1, 1)
		AddSpell(k[1], "Target_Predict", 1, 1)
		AddSpell(k[1], "Target_First_Aid", 1, 1)
		AddSpell(k[1], "Shout_Seek_PlayerVersion", 1, 1)
		AddSpell(k[1], "Target_Find_Weak_Spot_Survival", 1, 1)
		AddSpell(k[1], "Target_Deceive", 1, 1)
		AddSpell(k[1], "Target_Intimidate", 1, 1)
        AddSpell(k[1], "Target_Persuade", 1, 1)
        AddSpell(k[1], "Target_Taunt", 1, 1)
    end
end)
